version: '3'

services:
  flchat:
    build: .
    ports:
      - 5000:8000
    env_file: .env
    links:
      - psql:db
    restart: always

  psql:
    image: postgres:13
    env_file: .env-psql
    restart: always