"""empty message

Revision ID: 4576a45888ec
Revises: a9ec48b1efef
Create Date: 2021-05-22 13:12:38.992741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4576a45888ec'
down_revision = 'a9ec48b1efef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'channel_id')
    # ### end Alembic commands ###
