"""empty message

Revision ID: 537536b1b2cb
Revises: 52c6345737cc
Create Date: 2021-05-21 20:12:17.972804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537536b1b2cb'
down_revision = '52c6345737cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('id', sa.Integer(), nullable=False))

    op.alter_column('message', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('message', 'id')
    # ### end Alembic commands ###
