"""empty message

Revision ID: 5810c2e7a782
Revises: 4576a45888ec
Create Date: 2021-05-22 13:33:38.558321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5810c2e7a782'
down_revision = '4576a45888ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversation', ['channel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='unique')
    # ### end Alembic commands ###
