"""empty message

Revision ID: a9ec48b1efef
Revises: ad21e20a9774
Create Date: 2021-05-22 11:38:10.581274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec48b1efef'
down_revision = 'ad21e20a9774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('adder_id', sa.Integer(), nullable=False),
    sa.Column('added_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['adder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('adder_id', 'added_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
